REM  FIBONACCI SEQUENCE GENERATOR
REM  RELEASED INTO THE PUBLIC DOMAIN

REM  SETUP THE VARIABLES -- COUNTER, CURRENT VALUE AND LAST VALUE
10 LET I = 0
20 LET X = 1
30 LET Y = 0

REM  DISPLAY THE CURRENT ITERATION AND VALUE
40 PRINT "FIB: "; I, X

REM  ADD THE LAST VALUE TO THE CURRENT VALUE WHILE SAVING THE CURRENT VALUE
REM  AS THE NEW LAST VALUE
50 LET Z = X
60 LET X = X + Y
70 LET Y = Z

REM  INCREMENTING THE ITERATOR AND ABORTING WHEN IT'S TIME
80 LET I = I + 1
90 IF I <= 10 GOTO 40
